### ISSUE TITLE
What runtime parameters are required?

### ISSUE THREAD

**Issue by ottomattas** [xfold/LanguageBiasesInReddit#1]
We are trying to run this method on a dedicated AWS EC2 instance with 72GB of RAM which is exhausted quite fast, minutes after launching Run.py:
`Jan  4 11:55:35 ip-172-31-12-151 kernel: Out of memory: Kill process 4727 (python3) score 990 or sacrifice child`

Can you share more details on your runtime environment this was successfully ran on?

**Comment by xfold** [comment]
The models presented in the paper were trained using an Intel i5-9600K @3.70GHz with 32GB RAM, and an NVIDIA TitanXP GPU, so I guess you shouldn't have many problems with the current setup -- provided the datasets have a similar size.

To get it running maybe you could try with a smaller dataset and see if you can train the model and identify the biased words correctly. If the problem appears when discovering the biased words, maybe it's because of a super-large vocabulary -- in which case I would try first reducing it (e.g. by only considering nouns, for instance) to get it running.

**Comment by ottomattas** [comment]
Thanks! Really helps to put your work and implementation into perspective for our own project.

**Comment by ottomattas** [comment]
Thanks! Really helps to put your work and implementation into perspective for our own project.
